name: pdrtests
channels:
  - conda-forge
dependencies:
  - python=3.9
  - clize
  - cytoolz
  - numpy
  - pandas
  - git
  - dustgoggles
  - pds4_tools
  - pip
  - pyarrow
  - pytest
  - python-Levenshtein
  - multidict
  - more-itertools
  - pvl
  - astropy
  - jupyter
  - pillow
  - matplotlib
  - boto3
  - clize
  - fire
  - flask
  - requests
  - rich
  - sh
  - pip:
      - git+https://github.com/MillionConcepts/killscreen.git