name: pdrtests
channels:
  - conda-forge
dependencies:
  - python>=3.9
  # mostly hostess dependencies
  - boto3
  - dill
  - fabric
  - fire
  - invoke
  - pandas>=2.0.0
  - pdr
  - pip
  - pyarrow>=9.0.0
  - protobuf
  - psutil
  - pympler
  - python-magic
  - pyyaml
  - requests
  - rich
  - textual
  - hostess
