name: pdrtests
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - boto3
  - clize
  - fire
  - flask
  - pdr
  - pyarrow
  - pytest
  - requests
  - rich
  - sh
  - pip:
      - git+https://github.com/MillionConcepts/killscreen.git
