name: pdrtests
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - astropy
  - boto3
  - cytoolz
  - dill
  - dustgoggles
  - fabric
  - fire
  - git
  - invoke
  - jupyter
  - matplotlib
  - more-itertools
  - multidict
  - numpy
  - pandas>=2.0.0
  - pds4_tools
  - pillow
  - pip
  - protobuf
  - psutil
  - pvl
  - pympler
  - pytest
  - python-Levenshtein
  - python-magic
  - pyyaml
  - requests
  - rich
  - textual
  - pip:
      - git+https://github.com/MillionConcepts/hostess.git