name: pdrtests
channels:
  - conda-forge
dependencies:
  - python=3.9
  - boto3
  - clize
  - fire
  - flask
  - pdr
  - pip
  - pyarrow >= 9.0.0
  - pytest
  - requests
  - rich
  - pip:
      - git+https://github.com/MillionConcepts/killscreen.git
