from mission_scrape import select_and_scrape

"""These should be database file names that contain the relevant file information from the spider/scrapers."""
cdr_file = 'img_lroc_cdr_size_corrected.csv'
edr_file = 'img_lroc_edr_size_corrected.csv'
rdr_file = 'img_lroc_rdr_size_corrected.csv'

"""This is a dictionary of information about each file type:
    dataset: the name of the dataset type (this will be the name of the folder these data are downloaded into
    and the name of the dataset in datasets.py for testing
    database_file: the database file that contains the file information for this data type. for some mission this will
    all be the same, others are spread out between nodes or scraping sessions
    fn_must_contain: a list of strings that must be in this file name to differentiate it from the other types in the
    database file
    url_must_contain: an optional additional list of strings that must be in the url to differentiate this from other
    types in the database file."""
file_information = {1: {'dataset': 'NAC_CDR_if',
                        'database_file': cdr_file,
                        "fn_must_contain": ['M', '.IMG'],
                        "url_must_contain": ['NAC']},
                    2: {'dataset': 'NAC_CDR_rad',
                        'database': cdr_file,
                        "fn_must_contain": ['S', '.IMG'],
                        "url_must_contain": ['NAC']},
                    3: {'dataset': 'WAC_CDR',
                        'database': cdr_file,
                        'fn_must_contain': ['.IMG'],
                        'url_must_contain': ['WAC']},
                    4: {'dataset': 'NAC_EDR',
                        'database': edr_file,
                        'fn_must_contain': ['.IMG'],
                        'url_must_contain': ['NAC']},
                    5: {'dataset': 'WAC_EDR',
                        'database': edr_file,
                        'fn_must_contain': ['.IMG'],
                        'url_must_contain': ['WAC']},
                    6: {'dataset': 'NAC_DTM',
                        'database': rdr_file,
                        'fn_must_contain': ['NAC_DTM', '.TIF'],
                        'url_must_contain': ['/DATA/']},
                    7: {'dataset': 'NAC_PHO',
                        'database': rdr_file,
                        'fn_must_contain': ['NAC_PHO', '.IMG'],
                        },
                    8: {'dataset': 'NAC_POLE',
                        'database': rdr_file,
                        'fn_must_contain': ['NAC_POLE', '.IMG'],
                        },
                    9: {'dataset': 'NAC_POLE_PSR',
                        'database': rdr_file,
                        'fn_must_contain': ['NAC_POLE_PSR', '.IMG'],
                        },
                    10: {'dataset': 'NAC_ROI',
                         'database': rdr_file,
                         'fn_must_contain': ['NAC_ROI', '.IMG'],
                         },
                    11: {'dataset': 'WAC_CSHADE',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_CSHADE', '.IMG'],
                         },
                    12: {'dataset': 'WAC_EMP',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_EMP', '.IMG'],
                         },
                    13: {'dataset': 'WAC_EMP_tl',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_EMP', '.TIF'],
                         'url_must_contain': ['/DATA/']},
                    14: {'dataset': 'WAC_HAPKE',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_HAPKE', '.IMG'],
                         },
                    15: {'dataset': 'WAC_HAPKE_tl',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_HAPKE', '.TIF'],
                         'url_must_contain': ['/DATA/']},
                    16: {'dataset': 'WAC_HAPKE_PARAMMAP',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC-HAPKEPARAMMAP', '.IMG'],
                         },
                    17: {'dataset': 'WAC_GLD100',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_GLD100', '.IMG'],
                         },
                    18: {'dataset': 'WAC_GLOBAL',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_GLOBAL', '.IMG'],
                         },
                    19: {'dataset': 'WAC_MOVIE',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_MOVIE', '.IMG'],
                         },
                    20: {'dataset': 'WAC_ORBITS',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_ORBITS', '.IMG'],
                         },
                    21: {'dataset': 'WAC_POLE_ILL',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_POLE_ILL', '.IMG'],
                         },
                    22: {'dataset': 'WAC_ROI',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_ROI', '.IMG'],
                         },
                    23: {'dataset': 'WAC_TIO2',
                         'database': rdr_file,
                         'fn_must_contain': ['WAC_TIO2', '.IMG'],
                         },
                    24: {'dataset': 'ANAGLYPH',
                         'database': rdr_file,
                         'fn_must_contain': ['ANAGLYPH', '.TIF'],
                         },
                    }
select_and_scrape('lroc', file_information)
